// Edit freely. A question is a string, or { text, choices: [...], multi: true } for tap-to-pick chips with a text follow-up.
const SECTIONS = [
  {
    title: 'The easy ones',
    blurb: 'A warm-up. Favourites, habits, the small stuff.',
    image: 'her-centre.jpg',
    questions: [
      'What’s your full name, and is there a nickname people close to you use?',
      'What’s your favourite food, and what would you order if you had to pick one meal forever?',
      'What’s your favourite artist or musician right now, and what’s the one song you’ve played the most this year?',
      'Which city have you lived in the longest?',
      'What’s your favourite colour?',
      { text: 'Do you prefer mornings or nights, and what does a typical weekday look like for you?', choices: ['Mornings', 'Nights'] },
      'What’s your favourite movie or TV show, and have you rewatched anything more than twice?',
      { text: 'Tea, coffee, or neither? How do you take it?', choices: ['Tea', 'Coffee', 'Neither'] },
      'What’s the last book you finished, or the one you’re on now?',
      'What’s your favourite place you’ve ever travelled to?',
      'Do you have any pets, or have you ever wanted one?',
      'What’s your go-to weekend activity?',
      'What’s a food you absolutely refuse to eat?',
      { text: 'Are you a planner or someone who goes with the flow?', choices: ['Planner', 'Go with the flow'] },
      'What languages do you speak besides English?',
    ],
  },
  {
    title: 'Your story',
    blurb: 'Where you come from, and how you got here.',
    image: 'her-left.jpg',
    questions: [
      'Where did you grow up, and what was it like there?',
      'What do you do for work, and how did you end up in that field?',
      'What’s your highest level of education, and what did you study?',
      'How many siblings do you have, and where do you sit among them?',
      'What’s your relationship like with your parents right now?',
      'Have you ever lived abroad, and if so, where and for how long?',
      'What’s one skill you have that most people don’t know about?',
      'What were you like as a child?',
      'What’s a goal you’re currently working towards?',
      'What does your ideal week look like when you have no obligations?',
    ],
  },
  {
    title: 'How you think',
    blurb: 'Opinions welcome. Strong ones especially.',
    image: 'her-right.jpg',
    questions: [
      'What’s a belief you hold that most people around you disagree with?',
      'If you could instantly become an expert in one subject, what would it be?',
      'What’s a topic you could talk about for hours without getting bored?',
      { text: 'Do you think people can really change, or do they stay the same at their core?', choices: ['People can change', 'They stay the same'] },
      'What’s a common piece of advice you think is overrated?',
      'Which historical period would you choose to live in for a year?',
      'What do you think is the biggest problem facing your generation?',
      { text: 'Are you more of a risk-taker or someone who plays it safe, and where did that come from?', choices: ['Risk-taker', 'Play it safe'] },
      'What’s a decision you made that you’re still thinking about?',
      { text: 'Do you believe in fate, or do you think we make our own paths?', choices: ['Fate', 'We make our own paths'] },
    ],
  },
  {
    title: 'The deep end',
    blurb: 'Only what you’re comfortable sharing. Skipping is always allowed.',
    image: 'her-centre.jpg',
    questions: [
      'What’s something you’ve overcome that you’re proud of but rarely talk about?',
      'What makes you feel most loved by someone?',
      'What’s a fear you’ve never admitted to anyone?',
      'Who has influenced you the most, and how?',
      'What does a bad day look like for you, and what helps you recover?',
      'What’s something you’re still healing from, if you’re comfortable sharing?',
      'When do you feel most like yourself?',
      'What’s the kindest thing someone has ever done for you?',
      { text: 'How do you usually handle conflict: do you confront it, avoid it, or wait it out?', choices: ['Confront it', 'Avoid it', 'Wait it out'] },
      'What do you need from a partner that you haven’t always gotten?',
    ],
  },
  {
    title: 'Us',
    blurb: 'The last five. The ones I’m most curious about.',
    image: 'her-left.jpg',
    questions: [
      'What are your red flags in people, the things that make you lose interest quickly?',
      'What does a perfect date look like to you?',
      { text: 'How do you like to receive affection: words, time, gifts, touch, or acts of service?', choices: ['Words', 'Time', 'Gifts', 'Touch', 'Acts of service'], multi: true },
      'What’s something you’re looking for right now that you haven’t found yet?',
      'If we were still getting to know each other a year from now, what would you want me to have learned about you by then?',
    ],
  },
]
